[changelog]
header = ""
body = """
## What's Changed\n
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
split_commits = false
commit_parsers = [
  { message = "^feat", group = "Features" },
  { message = "^fix", group = "Bug Fixes" },
  { message = "^perf", group = "Performance" },
  { message = "^refactor", group = "Refactor" },
  { message = "^doc", group = "Documentation" },
  { message = "^style", group = "Styling" },
  { message = "^test", group = "Testing" },
  { message = "^chore", skip = true },
  { message = "^ci", skip = true },
]
protect_breaking_commits = false
filter_commits = false
topo_order = false
sort_commits = "oldest"
